### ISSUE TITLE
Evaluate alternative to jsverify

### ISSUE THREAD

**Issue by stefanobaghino-da** [digital-asset/daml-js#37]
This project is currently using [jsverify](https://github.com/jsverify/jsverify) for property-based testing as [it is currently inactive and looking for a new maintainer.](https://github.com/jsverify/jsverify/issues/299) It could be worth evaluating alternatives to it. [fast-check](https://github.com/dubzzz/fast-check) could be a good choice.

Note that this ticket clashes with #31.

**Comment by dubzzz** [comment]
Two coming soon PRs for recursive types in fast-check might make your migration easier 😁

See https://github.com/dubzzz/fast-check/pull/377 and https://github.com/dubzzz/fast-check/pull/378
Still some works to do before merging them but it is on its way

**Comment by stefanobaghino-da** [comment]
Thank you so much @dubzzz. I will definitely check it out as soon as I get back to this project (should be rather soon, hopefully).

**Comment by dubzzz** [comment]
You might be interesting by this repo: https://github.com/dubzzz/jsverify-to-fast-check

**Comment by stefanobaghino-da** [comment]
No longer relevant.

**Comment by dubzzz** [comment]
Still using jsverify?

**Comment by stefanobaghino-da** [comment]
Yes, but the project has been deprecated a long time ago at this point. It's unfortunate, I had a nice time working on it and found out about some amazing tools and libraries, including yours. Thanks anyway for the interest!
