### ISSUE TITLE
Needs update to NodeJS version support

### ISSUE THREAD

**Issue by smallbatch-apps** [digital-asset/daml-js#91]
Current version only supports a maximum version of 10.x. This version is not current and is going into maintenance mode from April 2020. The current Node LTS version is 12, and that should be the current support. 

I'm not sure that the version number couldn't just be bumped without any code changes.

**Comment by cocreature** [comment]
hi @smallbatch-apps, sorry for the delay. We just made a new release which supports NodeJS 12.
